#include "CMS3.h"
CMS3 cms3;
namespace tas {
	const float &evt_pfmet() { return cms3.evt_pfmet(); }
	const float &evt_pfmetPhi() { return cms3.evt_pfmetPhi(); }
	const float &evt_trackmet() { return cms3.evt_trackmet(); }
	const float &evt_trackmetPhi() { return cms3.evt_trackmetPhi(); }
	const float &evt_pfsumet() { return cms3.evt_pfsumet(); }
	const float &evt_pfmetSig() { return cms3.evt_pfmetSig(); }
	const int &evt_event() { return cms3.evt_event(); }
	const int &evt_lumiBlock() { return cms3.evt_lumiBlock(); }
	const int &evt_run() { return cms3.evt_run(); }
	const bool &filt_csc() { return cms3.filt_csc(); }
	const bool &filt_hbhe() { return cms3.filt_hbhe(); }
	const bool &filt_hcallaser() { return cms3.filt_hcallaser(); }
	const bool &filt_ecaltp() { return cms3.filt_ecaltp(); }
	const bool &filt_trkfail() { return cms3.filt_trkfail(); }
	const bool &filt_eebadsc() { return cms3.filt_eebadsc(); }
	const bool &evt_isRealData() { return cms3.evt_isRealData(); }
	const float &scale1fb() { return cms3.scale1fb(); }
	const float &evt_xsec_incl() { return cms3.evt_xsec_incl(); }
	const float &evt_kfactor() { return cms3.evt_kfactor(); }
	const float &gen_met() { return cms3.gen_met(); }
	const float &gen_metPhi() { return cms3.gen_metPhi(); }
	const float &njets() { return cms3.njets(); }
	const float &ht() { return cms3.ht(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets() { return cms3.jets(); }
	const vector<float> &jets_disc() { return cms3.jets_disc(); }
	const TString &sample() { return cms3.sample(); }
	const int &nFOs_SS() { return cms3.nFOs_SS(); }
	const int &nvtx() { return cms3.nvtx(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &p4() { return cms3.p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &tag_p4() { return cms3.tag_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &dilep_p4() { return cms3.dilep_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &mc_p4() { return cms3.mc_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &mc_motherp4() { return cms3.mc_motherp4(); }
	const int &id() { return cms3.id(); }
	const bool &isPF() { return cms3.isPF(); }
	const int &idx() { return cms3.idx(); }
	const float &dxyPV() { return cms3.dxyPV(); }
	const float &dZ() { return cms3.dZ(); }
	const float &dxyPV_err() { return cms3.dxyPV_err(); }
	const int &motherID() { return cms3.motherID(); }
	const int &mc_id() { return cms3.mc_id(); }
	const float &RelIso03() { return cms3.RelIso03(); }
	const float &RelIso03EA() { return cms3.RelIso03EA(); }
	const float &RelIso03DB() { return cms3.RelIso03DB(); }
	const bool &passes_SS_tight_v3() { return cms3.passes_SS_tight_v3(); }
	const bool &passes_SS_tight_noiso_v3() { return cms3.passes_SS_tight_noiso_v3(); }
	const bool &passes_SS_fo_v3() { return cms3.passes_SS_fo_v3(); }
	const bool &passes_SS_fo_noiso_v3() { return cms3.passes_SS_fo_noiso_v3(); }
	const bool &passes_SS_fo_looseMVA_v3() { return cms3.passes_SS_fo_looseMVA_v3(); }
	const bool &passes_SS_fo_looseMVA_noiso_v3() { return cms3.passes_SS_fo_looseMVA_noiso_v3(); }
	const bool &passes_HAD_veto_v3() { return cms3.passes_HAD_veto_v3(); }
	const bool &passes_HAD_veto_noiso_v3() { return cms3.passes_HAD_veto_noiso_v3(); }
	const bool &passes_HAD_loose_v3() { return cms3.passes_HAD_loose_v3(); }
	const bool &passes_HAD_loose_noiso_v3() { return cms3.passes_HAD_loose_noiso_v3(); }
	const bool &passes_POG_vetoID() { return cms3.passes_POG_vetoID(); }
	const bool &passes_POG_looseID() { return cms3.passes_POG_looseID(); }
	const bool &passes_POG_mediumID() { return cms3.passes_POG_mediumID(); }
	const bool &passes_POG_tightID() { return cms3.passes_POG_tightID(); }
	const float &ip3d() { return cms3.ip3d(); }
	const float &ip3derr() { return cms3.ip3derr(); }
	const int &type() { return cms3.type(); }
	const float &mt() { return cms3.mt(); }
	const float &ptrelv0() { return cms3.ptrelv0(); }
	const float &ptrelv1() { return cms3.ptrelv1(); }
	const float &miniiso() { return cms3.miniiso(); }
	const float &miniisoDB() { return cms3.miniisoDB(); }
	const float &reliso04() { return cms3.reliso04(); }
	const float &annulus04() { return cms3.annulus04(); }
	const float &iso03sumPt() { return cms3.iso03sumPt(); }
	const float &iso03emEt() { return cms3.iso03emEt(); }
	const float &iso03hadEt() { return cms3.iso03hadEt(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &jet_close_lep() { return cms3.jet_close_lep(); }
	const float &ptratio() { return cms3.ptratio(); }
	const int &tag_charge() { return cms3.tag_charge(); }
	const bool &tag_HLTLeadingLeg() { return cms3.tag_HLTLeadingLeg(); }
	const int &tag_HLT_Ele25WP60_Ele8_Mass55_LeadingLeg() { return cms3.tag_HLT_Ele25WP60_Ele8_Mass55_LeadingLeg(); }
	const int &tag_HLT_Ele25WP60_SC4_Mass55_LeadingLeg() { return cms3.tag_HLT_Ele25WP60_SC4_Mass55_LeadingLeg(); }
	const int &tag_HLT_Ele33_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg() { return cms3.tag_HLT_Ele33_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg() { return cms3.tag_HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg() { return cms3.tag_HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg() { return cms3.tag_HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele33_CaloIdM_TrackIdM_PFJet30_ElectronLeg() { return cms3.tag_HLT_Ele33_CaloIdM_TrackIdM_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele23_CaloIdM_TrackIdM_PFJet30_ElectronLeg() { return cms3.tag_HLT_Ele23_CaloIdM_TrackIdM_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele18_CaloIdM_TrackIdM_PFJet30_ElectronLeg() { return cms3.tag_HLT_Ele18_CaloIdM_TrackIdM_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele12_CaloIdM_TrackIdM_PFJet30_ElectronLeg() { return cms3.tag_HLT_Ele12_CaloIdM_TrackIdM_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Ele8_CaloIdM_TrackIdM_PFJet30_ElectronLeg() { return cms3.tag_HLT_Ele8_CaloIdM_TrackIdM_PFJet30_ElectronLeg(); }
	const int &tag_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_TrailingLeg() { return cms3.tag_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_TrailingLeg(); }
	const int &tag_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_LeadingLeg() { return cms3.tag_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_LeadingLeg(); }
	const int &tag_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_TrailingLeg() { return cms3.tag_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_TrailingLeg(); }
	const int &tag_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_LeadingLeg() { return cms3.tag_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_LeadingLeg(); }
	const int &probe_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_TrailingLeg() { return cms3.probe_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_TrailingLeg(); }
	const int &probe_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_LeadingLeg() { return cms3.probe_HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_LeadingLeg(); }
	const int &probe_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_TrailingLeg() { return cms3.probe_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_TrailingLeg(); }
	const int &probe_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_LeadingLeg() { return cms3.probe_HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_LeadingLeg(); }
	const float &dilep_mass() { return cms3.dilep_mass(); }
	const bool &isRandom() { return cms3.isRandom(); }
	const float &sigmaIEtaIEta_full5x5() { return cms3.sigmaIEtaIEta_full5x5(); }
	const float &sigmaIEtaIEta() { return cms3.sigmaIEtaIEta(); }
	const float &etaSC() { return cms3.etaSC(); }
	const float &dEtaIn() { return cms3.dEtaIn(); }
	const float &dPhiIn() { return cms3.dPhiIn(); }
	const float &hOverE() { return cms3.hOverE(); }
	const float &ecalEnergy() { return cms3.ecalEnergy(); }
	const float &eOverPIn() { return cms3.eOverPIn(); }
	const bool &conv_vtx_flag() { return cms3.conv_vtx_flag(); }
	const int &exp_innerlayers() { return cms3.exp_innerlayers(); }
	const int &charge() { return cms3.charge(); }
	const int &sccharge() { return cms3.sccharge(); }
	const int &ckf_charge() { return cms3.ckf_charge(); }
	const bool &threeChargeAgree() { return cms3.threeChargeAgree(); }
	const float &mva() { return cms3.mva(); }
	const float &tkIso() { return cms3.tkIso(); }
	const float &ecalIso() { return cms3.ecalIso(); }
	const float &hcalIso() { return cms3.hcalIso(); }
	const float &ecalPFClusterIso() { return cms3.ecalPFClusterIso(); }
	const float &hcalPFClusterIso() { return cms3.hcalPFClusterIso(); }
	const int &ckf_laywithmeas() { return cms3.ckf_laywithmeas(); }
	const float &sigmaIPhiIPhi_full5x5() { return cms3.sigmaIPhiIPhi_full5x5(); }
	const float &e1x5_full5x5() { return cms3.e1x5_full5x5(); }
	const float &e5x5_full5x5() { return cms3.e5x5_full5x5(); }
	const float &r9_full5x5() { return cms3.r9_full5x5(); }
	const float &etaSCwidth() { return cms3.etaSCwidth(); }
	const float &phiSCwidth() { return cms3.phiSCwidth(); }
	const float &eSCRaw() { return cms3.eSCRaw(); }
	const float &eSCPresh() { return cms3.eSCPresh(); }
	const float &ckf_chi2() { return cms3.ckf_chi2(); }
	const int &ckf_ndof() { return cms3.ckf_ndof(); }
	const float &chi2() { return cms3.chi2(); }
	const int &ndof() { return cms3.ndof(); }
	const float &fbrem() { return cms3.fbrem(); }
	const float &eOverPOut() { return cms3.eOverPOut(); }
	const float &dEtaOut() { return cms3.dEtaOut(); }
	const int &pid_PFMuon() { return cms3.pid_PFMuon(); }
	const float &gfit_chi2() { return cms3.gfit_chi2(); }
	const float &gfit_ndof() { return cms3.gfit_ndof(); }
	const int &gfit_validSTAHits() { return cms3.gfit_validSTAHits(); }
	const int &numberOfMatchedStations() { return cms3.numberOfMatchedStations(); }
	const int &validPixelHits() { return cms3.validPixelHits(); }
	const int &nlayers() { return cms3.nlayers(); }
	const float &chi2LocalPosition() { return cms3.chi2LocalPosition(); }
	const float &trkKink() { return cms3.trkKink(); }
	const int &validHits() { return cms3.validHits(); }
	const int &lostHits() { return cms3.lostHits(); }
	const int &exp_outerlayers() { return cms3.exp_outerlayers(); }
	const float &segmCompatibility() { return cms3.segmCompatibility(); }
	const int &HLT_Mu8_TrkIsoVVL() { return cms3.HLT_Mu8_TrkIsoVVL(); }
	const int &HLT_Mu17_TrkIsoVVL() { return cms3.HLT_Mu17_TrkIsoVVL(); }
	const int &HLT_Mu24_TrkIsoVVL() { return cms3.HLT_Mu24_TrkIsoVVL(); }
	const int &HLT_Mu34_TrkIsoVVL() { return cms3.HLT_Mu34_TrkIsoVVL(); }
	const int &HLT_Mu8() { return cms3.HLT_Mu8(); }
	const int &HLT_Mu17() { return cms3.HLT_Mu17(); }
	const int &HLT_Mu24() { return cms3.HLT_Mu24(); }
	const int &HLT_Mu34() { return cms3.HLT_Mu34(); }
	const int &HLT_Mu10_CentralPFJet30_BTagCSV0p5PF() { return cms3.HLT_Mu10_CentralPFJet30_BTagCSV0p5PF(); }
	const int &HLT_IsoMu20() { return cms3.HLT_IsoMu20(); }
	const int &HLT_IsoTkMu20() { return cms3.HLT_IsoTkMu20(); }
	const int &HLT_Mu10_CentralPFJet30_BTagCSV0p54PF() { return cms3.HLT_Mu10_CentralPFJet30_BTagCSV0p54PF(); }
	const int &HLT_IsoMu24_eta2p1() { return cms3.HLT_IsoMu24_eta2p1(); }
	const int &HLT_IsoTkMu24_eta2p1() { return cms3.HLT_IsoTkMu24_eta2p1(); }
	const int &HLT_IsoMu27() { return cms3.HLT_IsoMu27(); }
	const int &HLT_IsoTkMu27() { return cms3.HLT_IsoTkMu27(); }
	const int &HLT_Mu45_eta2p1() { return cms3.HLT_Mu45_eta2p1(); }
	const int &HLT_Mu50() { return cms3.HLT_Mu50(); }
	const int &HLT_Ele8_CaloIdM_TrackIdM_PFJet30() { return cms3.HLT_Ele8_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele12_CaloIdM_TrackIdM_PFJet30() { return cms3.HLT_Ele12_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele18_CaloIdM_TrackIdM_PFJet30() { return cms3.HLT_Ele18_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele23_CaloIdM_TrackIdM_PFJet30() { return cms3.HLT_Ele23_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele33_CaloIdM_TrackIdM_PFJet30() { return cms3.HLT_Ele33_CaloIdM_TrackIdM_PFJet30(); }
	const int &HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30() { return cms3.HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30() { return cms3.HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30() { return cms3.HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele33_CaloIdL_TrackIdL_IsoVL_PFJet30() { return cms3.HLT_Ele33_CaloIdL_TrackIdL_IsoVL_PFJet30(); }
	const int &HLT_Ele10_CaloIdM_TrackIdM_CentralPFJet30_BTagCSV0p5PF() { return cms3.HLT_Ele10_CaloIdM_TrackIdM_CentralPFJet30_BTagCSV0p5PF(); }
	const int &HLT_Ele10_CaloIdM_TrackIdM_CentralPFJet30_BTagCSV0p54PF() { return cms3.HLT_Ele10_CaloIdM_TrackIdM_CentralPFJet30_BTagCSV0p54PF(); }
	const int &HLT_Ele27_eta2p1_WP75_Gsf() { return cms3.HLT_Ele27_eta2p1_WP75_Gsf(); }
	const int &HLT_Ele27_WP85_Gsf() { return cms3.HLT_Ele27_WP85_Gsf(); }
	const int &HLT_Ele27_eta2p1_WPLoose_Gsf() { return cms3.HLT_Ele27_eta2p1_WPLoose_Gsf(); }
	const int &HLT_Ele27_eta2p1_WPTight_Gsf() { return cms3.HLT_Ele27_eta2p1_WPTight_Gsf(); }
	const int &HLT_Ele32_eta2p1_WP75_Gsf() { return cms3.HLT_Ele32_eta2p1_WP75_Gsf(); }
	const int &HLT_Ele32_eta2p1_WPLoose_Gsf() { return cms3.HLT_Ele32_eta2p1_WPLoose_Gsf(); }
	const int &HLT_Ele32_eta2p1_WPTight_Gsf() { return cms3.HLT_Ele32_eta2p1_WPTight_Gsf(); }
	const int &HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300() { return cms3.HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300(); }
	const int &HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL() { return cms3.HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL(); }
	const int &HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL() { return cms3.HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL(); }
	const int &HLT_DoubleMu8_Mass8_PFHT300() { return cms3.HLT_DoubleMu8_Mass8_PFHT300(); }
	const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL() { return cms3.HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL(); }
	const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL() { return cms3.HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL(); }
	const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ() { return cms3.HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ(); }
	const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ() { return cms3.HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ(); }
	const int &HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300() { return cms3.HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300(); }
	const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ() { return cms3.HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ(); }
}
